// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dev-skills/CockpitDashboard.tsx": () => import("../components/mockups/dev-skills/CockpitDashboard.tsx"),
  "./components/mockups/dev-skills/HeatmapMatrix.tsx": () => import("../components/mockups/dev-skills/HeatmapMatrix.tsx"),
  "./components/mockups/dev-skills/ProgressJourney.tsx": () => import("../components/mockups/dev-skills/ProgressJourney.tsx"),
  "./components/mockups/dev-skills/RadarSkillWeb.tsx": () => import("../components/mockups/dev-skills/RadarSkillWeb.tsx")
};
